// All svg components were generated by vue-svgicon using svg files
// https://github.com/MMF-FE/vue-svgicon
// Command: vsvg -s ./src/icons/svg -t ./src/icons/components --ext ts --es6

import './example'
import './eye-off'
import './eye-on'
import './form'
import './hamburger'
import './link'
import './nested'
import './password'
import './table'
import './tree'
import './user'
